### ISSUE TITLE
large input file encouter error?

### ISSUE THREAD

**Issue by Huan2012** [slhck/ffmpeg-debug-qp#3]
well, I tried the software, when the bitstream is small, the result is correct, but when the bitstream is large(my test is 10000 frames more, h264 bin format), the result text file and json file only contain 4400 frames around. I think is there a buffer is too small?

**Comment by slhck** [comment]
Thanks for reporting that issue!

Indeed there could be a problem with memory, since the data is not written out while it is being generated. 

I will have a look at whether this can be improved. 

Note that this is more or less a demo program that was not meant to be used in production environments.

**Comment by slhck** [comment]
Fixed in https://github.com/slhck/ffmpeg-debug-qp/commit/27f0b4c5da89c11fa3a53e1dbaba2f4d3df71fc4
